# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_Akritas <- function(truth, predict_times, unique_times, FX_train, FX_predict, lambda) {
    .Call(`_survivalmodels_C_Akritas`, truth, predict_times, unique_times, FX_train, FX_predict, lambda)
}

C_assert_increasing_surv <- function(x) {
    .Call(`_survivalmodels_C_assert_increasing_surv`, x)
}

